[package]
name = "sensirion-sht3x"
version = "0.1.0"
edition = "2021"
authors = ["Dustin Sweigart <dustin@swigg.net>"]
license = "MIT"
keywords = ["sensirion", "sensor", "temperature", "humidity", "sht3x"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/dustins/sensirion-sht3x"
repository = "https://github.com/dustins/sensirion-sht3x"
include = ["/**/*.rs", "/Cargo.toml", "/README.md"]
readme = "README.md"
publish = false

[dependencies]
bitflags = "2.9.0"
bytes = { version = "1.10.0", default-features = false }
embedded-hal = "1.0.0"
embedded-hal-async = { version = "1.0.0", optional = true }
log = "0.4.26"
measurements = "0.11.0"
sensirion-i2c = { git = "https://gitea.swigg.net/dustins/sensirion-i2c-rs.git", branch = "develop", version = "0.4.0", features = ["embedded-hal-async"] }

[dev-dependencies]
ctor = "0.4.0"
embedded-hal-mock = { version = "0.11.1", features = ["embedded-hal-async"] }
env_logger = "0.11.6"
futures = "0.3.31"

[features]
default = ["embedded-hal-async"]
embedded-hal-async = ["dep:embedded-hal-async", "embedded-hal-mock/embedded-hal-async"]
