[package]
name = "sensirion-sht3x"
version = "0.1.0"
edition = "2021"
authors = ["Dustin Sweigart <dustin@swigg.net>"]
license = "MIT"
keywords = ["sensirion", "sensor", "temperature", "humidity", "sht3x"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/swigg/sensirion-sht3x"
repository = "https://github.com/swigg/sensirion-sht3x"
include = ["/**/*.rs", "/Cargo.toml", "/README.md"]
readme = "README.md"
publish = false

[dependencies]
bitflags = "2.9.0"
bytes = { version = "1.10.0", default-features = false }
embedded-hal = "1.0.0"
embedded-hal-async = { version = "1.0.0", optional = true }
log = { version = "0.4.26", optional = true }
measurements = "0.11.0"
sensirion-i2c = "0.4.0"
sensirion-core = { git = "https://gitea.swigg.net/dustins/sensirion-core", branch = "develop" }

[dev-dependencies]
ctor = "0.4.0"
embedded-hal-mock = { version = "0.11.1" }
env_logger = "0.11.6"
futures = { version = "0.3.31", default-features = false, features = ["executor"] }

[features]
default = []
log = ["dep:log", "sensirion-core/log"]
embedded-hal-async = [
    "dep:embedded-hal-async",
    "embedded-hal-mock/embedded-hal-async",
    "sensirion-i2c/embedded-hal-async",
    "sensirion-core/embedded-hal-async"
]