name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/.gitignore"
      - "**/LICENSE.txt"
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        if: steps.cache-rust.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Run command
        run: cargo build --release --all-features

      - name: Run command
        run: cargo fmt --all -- --check

      - name: Run command
        run: cargo clippy --all-features --workspace -- --warn warnings